services:
  # cvat_db: # For modifying port mapping of DB to avoid conflicts with existing PostgreSQL instances
  #   ports: [] # Remove mappings (if using docker-compose.dev.yml)
  #   #  - '5433:5432' # Or instead change host port 5432-->5433

  cvat_server:
    environment:
      CVAT_SERVERLESS: 1
      CVAT_NUCLIO_HOST: ${CVAT_NUCLIO_HOST:-localhost}
      CVAT_NUCLIO_INVOKE_METHOD: 'dashboard'

  cvat_worker_annotation:
    environment:
      CVAT_NUCLIO_HOST: ${CVAT_NUCLIO_HOST:-localhost}
      CVAT_NUCLIO_INVOKE_METHOD: 'dashboard'

  cvat_ui: # adapted from docker-compose.dev.yml, needed for custom plugins with UI components such as SAM2
    build:
      context: .
      args:
        http_proxy:
        https_proxy:
        no_proxy:
        socks_proxy:
        CLIENT_PLUGINS: ${CLIENT_PLUGINS}
      dockerfile: Dockerfile.ui
